/*
 * c3_wrapper is a data wrapper, which defines an interface between c3.js and dpi_oper.js
 * These API offer a convenient way to update the chart with data from dpi_oper.js
 * C3 chart must be generated by c3.js library, and update events can be registered with this API.
 *
 * Notice:
 *  Only allow to use data.row() format currently.
 *  One chart is only allowed to connect to one kind of data
 *
 * TODO:
 *  
 *  connectData(chart, id, filter, size=10):
 *      chart: chart object created by c3.js
 *      id: ipv4 or dpid
 *      type: 'dpi' or 'port'
 *      size: size of history
 *
 *  disconnectData(chart):
 *      disconnect the chart data flow
 *
 *  setHistorySize(size):
 *      set the number of nodes shown in the chart.
 *      if the size is greater than that of present, append new data.
 *      else if size is less than that of present, only keep the latest number of data.
 *
 *  setType(type):
 *      'dpi' or 'port'.
 *      clear history data and transfer type between dpi and port.
 *
 *  clearData(chart):
 *      clear history data
 *      
 * */

function c3_wrapper(dpi_oper) {
    this.manager; 
    this.idCnt; // use increment number as id. According to ES5, id can up to 2^53-1.
    this.dpi_oper;
    this.tryPeriod; // if dpi_oper not ready, try after 100ms

    /* constructor */

    this.manager = [];  // [connections..]
    this.idCnt = 0;
    this.dpi_oper = null;
    this.tryPeriod = 100; // try to connect dpi_oper every 100ms at most 10 times
    this.tryLimit = 10;

    this.dpi_oper = dpi_oper; // init dpi_oper
}

/**********************************
 *  Helper function
 **********************************/

c3_wrapper.prototype.genId = function() {
    return this.idCnt++;
}

/*
 * connFilter define which data should be collected from dpi_oper
 * if dpi filter is null, then it will collect all dpi data.
 * */
c3_wrapper.prototype.setConnFilter = function(filter, conn) {
    if(!filter.hasOwnProperty('dpi'))
        throw "lack of dpi field";
    if(!filter.hasOwnProperty('port'))
        throw "lack of port field";

    /* set port filter */
    if(filter['port'] == null) {
        conn['connFilter']['port'] = ['rx_pkt', 'rx_bytes', 'tx_pkt', 'tx_bytes', 'tot_pkt', 'tot_bytes'];
    }
    else if(typeof filter['port'] === 'string') {
        // one param
		if(!this.isPortInfo(filter['port']))
			throw "wrong port field name: "+filter['port'];
        conn['connFilter']['port'].push(filter['port']);
    }
    else if(Object.prototype.toString.call(filter['port']) === '[object Array]') {
		for(var x in filter['port']) {
			if(!this.isPortInfo(filter['port'][x]))
				throw "wrong port field name: "+filter['port'][x];
		}
        conn['connFilter']['port'] = filter['port'].slice();
    }
    else
        throw "wrong port type";

    /* set dpi filter */
    if(filter['dpi'] == null) {
        conn['connFilter']['dpi'] = null; // this will collect all protocol info
    }
    else if(typeof filter['dpi'] === 'string') {
        // one param
        conn['connFilter']['dpi'].push(filter['dpi']);
    }
    else if(Object.prototype.toString.call(filter['dpi']) === '[object Array]') {
        conn['connFilter']['dpi'] = filter['dpi'].slice();
    }
    else
        throw "wrong dpi type";
}

/*
 * showFilter define which data should be shown in the chart
 * showFilter must be subset of connFilter
 * if dpi filter is null, then it will show protocols info. as many as possible
 * */
c3_wrapper.prototype.setShowFilter = function(showFilter, conn) {
    if(!showFilter.hasOwnProperty('dpi'))
        throw "lack of dpi field";
    if(!showFilter.hasOwnProperty('port'))
        throw "lack of port field";

    var dpi_list = showFilter['dpi'];
    var port_list = showFilter['port'];

    try {

        /* set port filter */
        if(port_list == null) {
            conn['showFilter']['port'] = conn['connFilter']['port'].slice();
        }
        else if(typeof port_list === 'string') {
            tryAdd(port_list, conn['connFilter']['port'], conn['showFilter']['port']);
        }
        else if(Object.prototype.toString.call(port_list) === '[object Array]') {
            for(var x in port_list) {
                tryAdd(port_list[x], conn['connFilter']['port'], conn['showFilter']['port']);
            }
        }
        else
            throw "wrong port type";

        /* set dpi filter */
        if(dpi_list == null) {
            if(conn['connFilter']['dpi'] == null)
                conn['showFilter']['dpi'] = null;
            else
                conn['showFilter']['dpi'] = conn['connFilter']['dpi'].slice();
        }
        else if(typeof dpi_list === 'string') {
            tryAdd(dpi_list, conn['connFilter']['dpi'], conn['showFilter']['dpi']);
        }
        else if(Object.prototype.toString.call(dpi_list) === '[object Array]') {
            for(var x in dpi_list) {
                tryAdd(dpi_list[x], conn['connFilter']['dpi'], conn['showFilter']['dpi']);
            }
        }
        else
            throw "wrong dpi type";
    }
    catch(err) {
        console.log(err);
        throw err; // rethrow
    }

    /* if element in carr, then push to iarr */
    function tryAdd(element, carr, iarr) {
        if(inArray(element, carr))
            iarr.push(element);
        else
            throw "showFilter must be subset of connFilter";
    }

    function inArray(str, arr) {
        for(var x in arr) {
            var tmp = arr[x];
            if(tmp == str)
                return true;
        }
        return false;
    }
}

c3_wrapper.prototype.isPortInfo= function(str) {
    if(str=='rx_pkt' || str=='rx_bytes' || str=='tx_pkt' || str=='tx_bytes' || str=='tot_pkt' || str=='tot_bytes')
        return true;
    else
        return false;
}

/*
 * connection:
 * {   'ref': obj, 
 *      'ts': []
 *      'tsCnt': int // ts counter, set chart => data: {x: 'ts'}
 *      'size': size, // For gauge, we can set it to 1 to keep only current value.
 *      'connFilter': {'dpi': [string ...], 'port': [string ...]}
 *      'showFilter': {'dpi': [string ...], 'port': [string ...]}
 *      'data': {'dpi': {protoName: []}, 'port': {rx_pkt: []}}
 *      'cb_name': string // Generate by c3_wrapper idCnt
 *      'id': int // ipv4 or dpid
 * }
 *  
 * */
c3_wrapper.prototype.genConnection = function(chart, id, connFilter, showFilter, size) {
    var _id = this.genId();

    if(chart==null)
        throw "chart is null";

    if(size<=0)
        throw "size can not <= 0";

    var conn =  {ref: chart, ts: ['ts'], tsCnt: 0, size: size, connFilter: {'dpi': [], 'port': []}, showFilter: {'dpi': [], 'port': []}, data: {'dpi': {}, 'port': {}}, cb_name: _id, id: id};
    this.setConnFilter(connFilter, conn);
    this.setShowFilter(showFilter, conn);

    return conn;
}

/* check dpi_oper is ready */
c3_wrapper.prototype.isReady = function() {
    if(this.dpi_oper && this.dpi_oper.isReady()) {
        return true;
    }
    return false;
}


/**********************************
 *  API
 **********************************/

/*
 * XXX: not allow duplicated field in filter
 * */
c3_wrapper.prototype.connectData = function(chart, id, connFilter={dpi: null, port: null}, showFilter={dpi: null, port: null}, size=10, failTime=0) {

	if(failTime==this.tryLimit) {
		throw "can not connect dpi_oper";
	}

    /* wait for ready */
	if(!this.isReady()) {
		var _this = this;
		setTimeout(function(){_this.connectData(chart, id, connFilter, showFilter, size, failTime+1)}, this.tryPeriod);
		return;
	}

    var conn = this.genConnection(chart, id, connFilter, showFilter, size);
    //try {
        //_this = this; 
        //this.dpi_oper.regCallBack(type, conn.cb_name, id, function(data){
            //// this is chart, _this is c3_wrapper
            //var dpi = _this.dpi_oper;
            
        //}, chart)
    //}
    //catch(err) {
        //console.log("connectData error: "+err);
        //return;
    //}

    return conn;
}

c3_wrapper.prototype.disconnectData = function(chart) {

}

c3_wrapper.prototype.setHistorySize = function(size) {

}

c3_wrapper.prototype.setType = function(type) {

}

c3_wrapper.prototype.clearData = function(chart) {

}

